version: 1.2
notebooks:
  - format: JUPYTER
    path: /hello-world-r.ipynb
    language: R
    topic: Hello world in R
    authors:
      - name: David Steinberg
    publish: True
  - format: JUPYTER
    name: hello-figure-r
    path: /hello-figure-r.ipynb
    language: R
    topic: Basic R scatter plot
    publish: True
    authors:
      - name: David Steinberg
